#!/bin/bash

#try running: npm install -g watchify browser-sync babel-cli uglify-js
echo "Building Handler..."

mkdir -p dist && \
(babel --presets es2015 --source-type 'module' --watch src --out-dir .transpiled & \
  (sleep 5 && \
    (tee >(read && ./serve) \
       < <( \
           # (watchify .transpiled/handlers/custom/index.js -o '> dist/handler.min.js && echo "Built handler.js"' -v) & \
           (watchify .transpiled/handlers/custom/index.js -o 'uglifyjs -cm > dist/handler.min.js && echo "Built handler.js"' -v) & \
           (watchify .transpiled/ui/index.js -o '> dist/ui.js && echo "Built ui.js"' -v) \
          ))))
