#!/bin/bash

#try running: npm install -g watchify browser-sync babel-cli
echo "Building Handler..."

(babel --presets es2015 --source-type 'module' --watch src --out-dir .transpiled & \
  (sleep 5 && \
  tee >(read && browser-sync start --server --https --files "*.html|*.js") \
    < <(watchify .transpiled/handlers/custom/index.js -o '> handler.js && echo "Built handler.js"' -v)))
