#!/bin/bash

#try running: npm install -g watchify browser-sync babel-cli
echo "Building Handler..."

mkdir -p dist && \
(babel --presets es2015 --source-type 'module' --watch src --out-dir .transpiled & \
  (sleep 5 && \
    (tee >(read && browser-sync start --server --https --files "*.html|dist/*.js") \
       < <( \
            (watchify .transpiled/handlers/custom/index.js -o '> dist/handler.js && echo "Built handler.js"' -v) \
          & (watchify .transpiled/ui/index.js -o '> dist/ui.js && echo "Built ui.js"' -v) \
          ))))
